/* config.h.  Generated by configure.  */
/* config.h.in.  Generated automatically from configure.in by autoheader.  */
/* #undef ino_t */
#define HAVE_CONNECT 1
/* #undef HAVE_SHORT_INO_T */
/* #undef HAVE_GETOPT_LONG */
/* #undef REPLACE_INET_NTOA */
/* #undef REPLACE_INET_ATON */
#define HAVE_GETTIMEOFDAY_TZ 1
/* #undef ENABLE_IPV6 */
/* #undef HAVE_SOCKADDR_LEN */
#define HAVE_SOCKETPAIR 1

/* Define to the type of elements in the array set by `getgroups'. Usually
   this is either `int' or `gid_t'. */
#define GETGROUPS_T gid_t

/* Define if you have the <alloca.h> header file. */
#define HAVE_ALLOCA_H 1

/* Define if you have the <arpa/inet.h> header file. */
#define HAVE_ARPA_INET_H 1

/* Define if you have the <arpa/nameser.h> header file. */
#define HAVE_ARPA_NAMESER_H 1

/* Define if you have the `asprintf' function. */
#define HAVE_ASPRINTF 1

/* */
/* #undef HAVE_BROKEN_READDIR */

/* */
#define HAVE_C99_VSNPRINTF 1

/* Define if you have the `chmod' function. */
#define HAVE_CHMOD 1

/* Define if you have the `chown' function. */
#define HAVE_CHOWN 1

/* Define if you have the <compat.h> header file. */
/* #undef HAVE_COMPAT_H */

/* */
#define HAVE_CONNECT 1

/* Define if you have the <ctype.h> header file. */
#define HAVE_CTYPE_H 1

/* Define if you have the <dirent.h> header file, and it defines `DIR'. */
#define HAVE_DIRENT_H 1

/* */
#define HAVE_ERRNO_DECL 1

/* Define if you have the `fchmod' function. */
#define HAVE_FCHMOD 1

/* Define if you have the <fcntl.h> header file. */
#define HAVE_FCNTL_H 1

/* */
#define HAVE_FNMATCH 1

/* Define if you have the `fstat' function. */
#define HAVE_FSTAT 1

/* Define if you have the `getaddrinfo' function. */
#define HAVE_GETADDRINFO 1

/* Define if you have the `getcwd' function. */
#define HAVE_GETCWD 1

/* Define if you have the `getnameinfo' function. */
#define HAVE_GETNAMEINFO 1

/* */
#define HAVE_GETTIMEOFDAY_TZ 1

/* Define if you have the `glob' function. */
#define HAVE_GLOB 1

/* Define if you have the <glob.h> header file. */
#define HAVE_GLOB_H 1

/* Define if you have the <grp.h> header file. */
#define HAVE_GRP_H 1

/* Define if you have the `inet_ntop' function. */
#define HAVE_INET_NTOP 1

/* Define if you have the `inet_pton' function. */
#define HAVE_INET_PTON 1

/* Define if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define if you have the `lchown' function. */
#define HAVE_LCHOWN 1

/* Define if you have the `inet' library (-linet). */
/* #undef HAVE_LIBINET */

/* Define if you have the `nsl' library (-lnsl). */
/* #undef HAVE_LIBNSL */

/* Define if you have the `nsl_s' library (-lnsl_s). */
/* #undef HAVE_LIBNSL_S */

/* Define if you have the `popt' library (-lpopt). */
#define HAVE_LIBPOPT 1

/* Define if you have the `resolv' library (-lresolv). */
#define HAVE_LIBRESOLV 1

/* Define if you have the `socket' library (-lsocket). */
/* #undef HAVE_LIBSOCKET */

/* Define if you have the `link' function. */
#define HAVE_LINK 1

/* */
#define HAVE_LONGLONG 1

/* Define if you have the `mallinfo' function. */
#define HAVE_MALLINFO 1

/* Define if you have the <malloc.h> header file. */
#define HAVE_MALLOC_H 1

/* Define if you have the <mcheck.h> header file. */
#define HAVE_MCHECK_H 1

/* Define if you have the `memmove' function. */
#define HAVE_MEMMOVE 1

/* Define if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define if you have the `mknod' function. */
#define HAVE_MKNOD 1

/* Define if you have the `mtrace' function. */
#define HAVE_MTRACE 1

/* Define if you have the <ndir.h> header file, and it defines `DIR'. */
/* #undef HAVE_NDIR_H */

/* Define if you have the <netdb.h> header file. */
#define HAVE_NETDB_H 1

/* */
/* #undef HAVE_OFF64_T */

/* Define if you have the `readlink' function. */
#define HAVE_READLINK 1

/* remote shell is remsh not rsh */
#define HAVE_REMSH 0

/* */
#define HAVE_SECURE_MKSTEMP 1

/* Define if you have the `setgroups' function. */
#define HAVE_SETGROUPS 1

/* Define if you have the `setsid' function. */
#define HAVE_SETSID 1

/* */
/* #undef HAVE_SHORT_INO_T */

/* Define if you have the `snprintf' function. */
#define HAVE_SNPRINTF 1

/* Define if you have strct sockaddr_storage. */
#define HAVE_SOCKADDR_STORAGE 1

/* */
#define HAVE_SOCKETPAIR 1

/* Define if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define if you have the `strcasecmp' function. */
#define HAVE_STRCASECMP 1

/* Define if you have the `strchr' function. */
#define HAVE_STRCHR 1

/* Define if you have the `strdup' function. */
#define HAVE_STRDUP 1

/* Define if you have the `strerror' function. */
#define HAVE_STRERROR 1

/* Define if you have the `strftime' function. */
#define HAVE_STRFTIME 1

/* Define if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define if you have the `strlcat' function. */
/* #undef HAVE_STRLCAT */

/* Define if you have the `strlcpy' function. */
/* #undef HAVE_STRLCPY */

/* Define if you have the `strpbrk' function. */
#define HAVE_STRPBRK 1

/* Define if `st_rdev' is member of `struct stat'. */
#define HAVE_STRUCT_STAT_ST_RDEV 1

/* Define if you have the <sys/dir.h> header file, and it defines `DIR'. */
/* #undef HAVE_SYS_DIR_H */

/* Define if you have the <sys/fcntl.h> header file. */
#define HAVE_SYS_FCNTL_H 1

/* Define if you have the <sys/filio.h> header file. */
/* #undef HAVE_SYS_FILIO_H */

/* Define if you have the <sys/ioctl.h> header file. */
#define HAVE_SYS_IOCTL_H 1

/* Define if you have the <sys/mode.h> header file. */
/* #undef HAVE_SYS_MODE_H */

/* Define if you have the <sys/ndir.h> header file, and it defines `DIR'. */
/* #undef HAVE_SYS_NDIR_H */

/* Define if you have the <sys/param.h> header file. */
#define HAVE_SYS_PARAM_H 1

/* Define if you have the <sys/select.h> header file. */
#define HAVE_SYS_SELECT_H 1

/* Define if you have the <sys/socket.h> header file. */
#define HAVE_SYS_SOCKET_H 1

/* Define if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define if you have the <sys/sysctl.h> header file. */
#define HAVE_SYS_SYSCTL_H 1

/* Define if you have the <sys/time.h> header file. */
#define HAVE_SYS_TIME_H 1

/* Define if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define if you have the <sys/unistd.h> header file. */
#define HAVE_SYS_UNISTD_H 1

/* Define if you have the <sys/wait.h> header file. */
#define HAVE_SYS_WAIT_H 1

/* Define if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* */
/* #undef HAVE_UNSIGNED_CHAR */

/* */
#define HAVE_UTIMBUF 1

/* Define if you have the `utime' function. */
#define HAVE_UTIME 1

/* Define if you have the `utimes' function. */
#define HAVE_UTIMES 1

/* Define if you have the <utime.h> header file. */
#define HAVE_UTIME_H 1

/* Define if `utime(file, NULL)' sets file's timestamp to the present. */
#define HAVE_UTIME_NULL 1

/* Define if you have the `vsnprintf' function. */
#define HAVE_VSNPRINTF 1

/* Define if you have the `wait4' function. */
#define HAVE_WAIT4 1

/* Define if you have the `waitpid' function. */
#define HAVE_WAITPID 1

/* true if you have IPv6 */
#define INET6 1

/* */
/* #undef REPLACE_INET_ATON */

/* */
/* #undef REPLACE_INET_NTOA */

/* Define as the return type of signal handlers (`int' or `void'). */
#define RETSIGTYPE void

/* location of rsync on remote machine */
#define RSYNC_PATH "rsync"

/* default -e command */
#define RSYNC_RSH "ssh"

/* rsync release version */
#define RSYNC_VERSION "2.5.5"

/* The size of a `int', as computed by sizeof. */
#define SIZEOF_INT 4

/* The size of a `long', as computed by sizeof. */
#define SIZEOF_LONG 4

/* The size of a `short', as computed by sizeof. */
#define SIZEOF_SHORT 2

/* Define if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define if you can safely include both <sys/time.h> and <time.h>. */
#define TIME_WITH_SYS_TIME 1

/* Define if your processor stores words with the most significant byte first
   (like Motorola and SPARC, unlike Intel and VAX). */
/* #undef WORDS_BIGENDIAN */

/* Number of bits in a file offset, on hosts where this is settable. */
#define _FILE_OFFSET_BITS 64

/* Define _GNU_SOURCE so that we get all necessary prototypes */
#define _GNU_SOURCE 1

/* Define for large files, on AIX-style hosts. */
/* #undef _LARGE_FILES */

/* Define to `int' if <sys/types.h> doesn't define. */
/* #undef gid_t */

/* Define as `__inline' if that's what the C compiler calls it, or to nothing
   if it is not supported. */
/* #undef inline */

/* Define to `unsigned' if <sys/types.h> does not define. */
/* #undef ino_t */

/* Define to `int' if <sys/types.h> does not define. */
/* #undef mode_t */

/* Define to `long' if <sys/types.h> does not define. */
/* #undef off_t */

/* Define to `int' if <sys/types.h> does not define. */
/* #undef pid_t */

/* Define to `unsigned' if <sys/types.h> does not define. */
/* #undef size_t */

/* type to use in place of socklen_t if not defined */
/* #undef socklen_t */

/* Define to `int' if <sys/types.h> doesn't define. */
/* #undef uid_t */
